#!/usr/bin/env bash
set -euo pipefail

# Build the kernel bundle on Linux-native container storage.  macOS shared
# filesystems cannot safely host a fresh Linux source extraction.
SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_PATH
readonly BACKEND_REQUEST="${LIBKRUNFW_BUILD_BACKEND:-auto}"
readonly BUILD_DNS="${LIBKRUNFW_BUILD_DNS:-}"
readonly IMAGE="fedora:latest"
CONTAINER_NAME="libkrunfw-builder-$$-$(date +%s)"
readonly CONTAINER_NAME

backend=
builder_started=false
archive_dir=
archive_path=
candidate_path=

fail() {
    echo "error: $*" >&2
    exit 1
}

cleanup() {
    local status=$?
    if [[ "$builder_started" == true ]]; then
        if [[ "$backend" == container ]]; then
            container delete --force "$CONTAINER_NAME" >/dev/null 2>&1 || :
        else
            docker rm --force "$CONTAINER_NAME" >/dev/null 2>&1 || :
        fi
    fi
    # The candidate name is generated by mktemp and never points at a
    # caller-supplied path, so this cleanup owns it even if a failed copy
    # created a directory instead of the requested regular file.
    [[ -z "$candidate_path" ]] || find "$candidate_path" -depth -delete >/dev/null 2>&1 || :
    [[ -z "$archive_path" ]] || rm -f "$archive_path"
    [[ -z "$archive_dir" ]] || rmdir "$archive_dir" >/dev/null 2>&1 || :
    exit "$status"
}
trap cleanup EXIT

validate_dns_override() {
    local octet
    local -a octets

    [[ -z "$BUILD_DNS" ]] && return
    [[ "$BUILD_DNS" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || fail "LIBKRUNFW_BUILD_DNS must be an IPv4 address (got $BUILD_DNS)"
    IFS=. read -r -a octets <<<"$BUILD_DNS"
    for octet in "${octets[@]}"; do
        ((10#$octet <= 255)) || fail "LIBKRUNFW_BUILD_DNS must be an IPv4 address (got $BUILD_DNS)"
    done
}

select_backend() {
    case "$BACKEND_REQUEST" in
        auto)
            if command -v container >/dev/null 2>&1; then
                backend=container
            elif command -v docker >/dev/null 2>&1; then
                backend=docker
            else
                fail "no supported container backend found; install Apple's container CLI or Docker"
            fi
            ;;
        container|docker) backend="$BACKEND_REQUEST" ;;
        *) fail "LIBKRUNFW_BUILD_BACKEND must be auto, container, or docker (got $BACKEND_REQUEST)" ;;
    esac

    if [[ "$backend" == container ]]; then
        command -v container >/dev/null 2>&1 || fail "Apple container CLI is unavailable; install it or select docker"
        container system status >/dev/null 2>&1 || fail "Apple container service is unavailable; run 'container system start'"
    else
        command -v docker >/dev/null 2>&1 || fail "Docker is unavailable; install Docker or select container"
        docker info >/dev/null 2>&1 || fail "Docker daemon is unavailable; start Docker Desktop"
    fi
}

run_builder() {
    local -a run_options=(--detach --name "$CONTAINER_NAME")
    [[ -z "$BUILD_DNS" ]] || run_options+=(--dns "$BUILD_DNS")

    if [[ "$backend" == container ]]; then
        container run "${run_options[@]}" "$IMAGE" /usr/bin/sleep infinity >/dev/null
    else
        docker run "${run_options[@]}" "$IMAGE" /usr/bin/sleep infinity >/dev/null
    fi
}

builder_exec() {
    if [[ "$backend" == container ]]; then
        container exec "$CONTAINER_NAME" "$@"
    else
        docker exec "$CONTAINER_NAME" "$@"
    fi
}

builder_copy_in() {
    if [[ "$backend" == container ]]; then
        container copy "$archive_path" "$CONTAINER_NAME:/tmp/libkrunfw-source.tar"
    else
        docker cp "$archive_path" "$CONTAINER_NAME:/tmp/libkrunfw-source.tar"
    fi
}

builder_copy_out() {
    if [[ "$backend" == container ]]; then
        container copy "$CONTAINER_NAME:/work/kernel.c" "$candidate_path"
    else
        docker cp "$CONTAINER_NAME:/work/kernel.c" "$candidate_path"
    fi
}

create_source_archive() {
    archive_dir="$(mktemp -d "${TMPDIR:-/tmp}/libkrunfw-source.XXXXXX")"
    archive_path="$archive_dir/source.tar"
    # Keep tarball caches but never use extracted kernels or generated bundles
    # as source inputs to this native-storage build.
    tar -C "$SCRIPT_PATH" \
        --exclude=.git --exclude='./.git' \
        --exclude=kernel.c --exclude='./kernel.c' --exclude='.kernel.c.next.*' \
        --exclude='linux-*' --exclude='./linux-*' \
        --exclude=qboot.c --exclude=initrd.c --exclude=vmlinux \
        --exclude='*.dylib' --exclude='./*.dylib' \
        --exclude='*.so' --exclude='./*.so' \
        --exclude='*.so.*' --exclude='./*.so.*' \
        --exclude='*.dll' --exclude='./*.dll' \
        --exclude='*.exp' --exclude='./*.exp' \
        --exclude='*.lib' --exclude='./*.lib' \
        --exclude='*.obj' --exclude='./*.obj' \
        --exclude='*.pdb' --exclude='./*.pdb' \
        -cf "$archive_path" .
    [[ -s "$archive_path" ]] || fail "could not create source archive"
}

main() {
    validate_dns_override
    select_backend
    candidate_path="$(mktemp "$SCRIPT_PATH/.kernel.c.next.XXXXXX")"
    rm -f "$candidate_path"
    create_source_archive

    echo "==> libkrunfw backend: $backend"
    echo "==> Uploading filtered source snapshot"
    run_builder
    builder_started=true
    builder_exec /usr/bin/true
    builder_copy_in
    echo "==> Building kernel bundle in container-native /work"
    # shellcheck disable=SC2016 # The quoted program intentionally runs inside the container.
    builder_exec /bin/bash -lc 'mkdir -p /work && tar -xf /tmp/libkrunfw-source.tar -C /work && cd /work && dnf install -y "dnf-command(builddep)" python3-pyelftools curl && dnf builddep -y kernel && make -j"$(nproc)" kernel.c'
    echo "==> Publishing kernel.c result"
    builder_copy_out
    [[ -f "$candidate_path" && ! -L "$candidate_path" && -s "$candidate_path" ]] || fail "container did not produce a non-empty regular /work/kernel.c"
    mv -f "$candidate_path" "$SCRIPT_PATH/kernel.c"
    candidate_path=
    echo "==> Published $SCRIPT_PATH/kernel.c"
}

main "$@"
